spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/likelion
    username: root
    password: ha030618!@
    driver-class-name: com.mysql.cj.jdbc.Driver